<?php

function comment_buddy_menu() {
  $items = array();
  $items['comment_created'] = array(
    'title' => 'comment created',
    'page callback' => 'comment_buddy_comment_insert',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['comment_updated'] = array(
    'title' => 'comment updated',
    'page callback' => 'comment_buddy_comment_update',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['comment_deleted'] = array(
    'title' => 'comment deleted',
    'page callback' => 'comment_buddy_comment_delete',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
}

function comment_buddy_comment_insert() {
  drupal_set_message("Thank you! Comment submitted!");
}

function comment_buddy_comment_update() {
  drupal_set_message("Your comment has been changed.");
}

function comment_buddy_comment_delete() {
  drupal_set_message("Comment deleted. Good work eating your words.");
}
